#!/usr/bin/env ruby

require('irb/completion')
require('irb/ext/save-history')

ARGV << "--readline"

IRB.conf[:PROMPT_MODE]  = :SIMPLE
IRB.conf[:AUTO_INDENT]  = true
IRB.conf[:SAVE_HISTORY] = 2000
IRB.conf[:HISTORY_FILE] = File.expand_path("~/.irb-history")

begin
  require('rubygems')
  require('yaml')
  require('open-uri')
rescue LoadError => e
  $stderr.puts(e.to_s)
end
