##############################################################################
include ../mk/install.mk

##############################################################################
$(eval $(call INSTALL_DOT_FILE,Xdefaults))
$(eval $(call INSTALL_EXEC_DOT_FILE,xsession))
